const actionTypes = {
    WORK_ORDERS_LOAD_START: "WORK_ORDERS_LOAD_START",
    WORK_ORDERS_LOAD_SUCCESS: "WORK_ORDERS_LOAD_SUCCESS",
    WORK_ORDERS_LOAD_ERROR: "WORK_ORDERS_LOAD_ERROR"
}

export default actionTypes